{% set version = "0.1.4.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pool
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pool_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pool/pool_{{ version }}.tar.gz
  sha256: a299ea5e0976ab4721980395a070143b2f5a8ffd444ee21a00fbedfde05eb718

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dbi
    - r-r6
    - r-dbplyr
    - r-dplyr
    - r-later
  run:
    - r-base
    - r-dbi
    - r-r6
    - r-dbplyr
    - r-dplyr
    - r-later

test:
  commands:
    - $R -e "library('pool')"           # [not win]
    - "\"%R%\" -e \"library('pool')\""  # [win]

about:
  home: https://github.com/rstudio/pool
  license: GPL-3
  summary: Enables the creation of object pools, which make it less computationally expensive
    to fetch a new object. Currently the only supported pooled objects are 'DBI' connections.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: pool
# Type: Package
# Title: Object Pooling
# Version: 0.1.4.2
# Authors@R: c( person("Joe", "Cheng", email = "joe@rstudio.com", role = c("aut", "cre")), person("Barbara", "Borges", email = "barb.b.ribeiro@gmail.com", role = c("aut")), person(family = "RStudio", role = "cph") )
# Description: Enables the creation of object pools, which make it less computationally expensive to fetch a new object. Currently the only supported pooled objects are 'DBI' connections.
# License: GPL-3
# Depends: R (>= 3.0.0), methods
# Imports: DBI, R6, dplyr, dbplyr, later
# Suggests: testthat, tibble, RSQLite, RMySQL
# URL: https://github.com/rstudio/pool
# BugReports: https://github.com/rstudio/pool/issues
# LazyData: TRUE
# Collate: 'utils.R' 'scheduler.R' 'pool.R' 'pool-methods.R' 'object.R' 'DBI.R' 'DBI-connection-interpolate.R' 'DBI-connection-quote.R' 'DBI-connection-sql.R' 'DBI-connection-transaction.R' 'DBI-connection.R' 'DBI-driver.R' 'DBI-object-deprecated.R' 'DBI-object.R' 'DBI-pool.R' 'dbplyr.R'
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-01-04 18:30:23 UTC; jcheng
# Author: Joe Cheng [aut, cre], Barbara Borges [aut], RStudio [cph]
# Maintainer: Joe Cheng <joe@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-01-07 20:20:02 UTC
