appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: yDmP9Q+s9HRInIgrLRnjDJpbqIzs7MBvaK/Y9l9qFWqoWmwm6yPzZFyEDWZGJmg/BMGkE6a2gnXmFje30DuU5mNmu4mtzEtZwOaJ3WrvySnvhsjemqI3WdR5gLTOzCc1ZhchNdTb04p5F0gM+KPl47/baVj1mIvS94Ht7vl2br8eEX8eqEBaNpzSVe8g3FixTnL2X95G46wV6yVl09HARKTERTPAPj3Gbpzj6/77AxsLvnhokpZFNaJ71VIrrT04eP50JyobNG8iGsmUKWilydfdhDgZIa4oen+aEK2AoZRs8Kp/G4LDfoK3lqVbzQ1i6mQzGph9RhEiILBc8pNoG7Zv0u4bf+wgRBtt/zAv72+a596717YxWI4g/kf2MwSU2Mn8Rn16YKc9PthuQ6+Eju2glCCEo5LGGXJk9b5Zd/DODwgaRHUAnSr4gxfZOUrV43LN4QiBT3nSwLsok63ZL6wrU47RX//fplaC1vUD9fbFOI3NuT22GTZXF/Ph5CS/Z09GlBttDkb4RF5hBVoOlwx50nIhFc8MCTpLy4+YCR5Uo3KN7BjojoIPnAsjcUlkx8H3NdJ9DcMgi1yhwKxvWieMzfEsYFXsfK5oC/bX+nk+DBGV9D6nzZPaHzKt5XfcTjX2/f5eUHR62ti4h4GyUFfv8pHAephXNs2JE5uR7zk=
